"""
Generate a working Python connector from an approved ConnectorSpec.
The output is a standalone module with no framework dependencies —
just httpx and the standard library.
"""
from __future__ import annotations

import re
import textwrap
from pathlib import Path

from .schemas import ConnectorSpec, EndpointConfig, FieldMapping, Transformation


def generate_connector(spec: ConnectorSpec, output_dir: Path) -> Path:
    """
    Render connector code and write it to output_dir.
    Raises if the spec still has pending review flags.
    """
    if not spec.approved:
        pending = [f.id for f in spec.pending_flags()]
        raise ValueError(f"Spec has {len(pending)} pending flag(s): {pending}")

    code = _render_connector(spec)
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{_slugify(spec.api_name)}_connector.py"
    out_path.write_text(code, encoding="utf-8")
    return out_path


def _render_connector(spec: ConnectorSpec) -> str:
    class_name = _class_name(spec.api_name)
    send_event_methods = "\n\n".join(
        _render_endpoint_method(ep) for ep in spec.endpoints
    )
    transform_helpers = _render_transform_helpers(spec)

    auth_param = _auth_param(spec)
    path_params = _path_params(spec)
    init_params = ", ".join([auth_param] + path_params)
    init_assigns = "\n        ".join(
        [f"self._{p} = {p}" for p in [_param_name(spec)] + [p for p in path_params]]
    )
    auth_setup = _auth_setup(spec)

    return textwrap.dedent(f'''\
        """
        {spec.api_name} connector — generated by agent-built-connector.
        Spec version: {spec.spec_version}
        Generated at: {spec.generated_at.isoformat()}

        Do not edit by hand. Re-run the agent to regenerate.
        """
        from __future__ import annotations

        import hashlib
        import time
        from typing import Any, Optional

        import httpx

        BASE_URL = "{spec.base_url}"
        DEFAULT_TIMEOUT = 30.0


        {transform_helpers}


        class {class_name}:
            def __init__(self, {init_params}):
                {init_assigns}
                self._client = httpx.Client(
                    base_url=BASE_URL,
                    timeout=DEFAULT_TIMEOUT,
                    {auth_setup}
                )

        {textwrap.indent(send_event_methods, "    ")}

            def close(self) -> None:
                self._client.close()

            def __enter__(self) -> "{class_name}":
                return self

            def __exit__(self, *_: Any) -> None:
                self.close()
        ''')


def _render_endpoint_method(ep: EndpointConfig) -> str:
    method_name = _slugify(ep.name)
    path = ep.path

    if ep.batch:
        return _render_batch_method(ep, method_name, path)
    return _render_single_method(ep, method_name, path)


def _render_batch_method(ep: EndpointConfig, method_name: str, path: str) -> str:
    batch = ep.batch
    # Build the path substitution for path params
    path_sub = _path_substitution(ep, path)

    field_prepare_lines = _render_field_preparation(ep.body_fields, indent=12)
    all_or_nothing_comment = (
        "# NOTE: API rejects the entire batch on any single invalid item.\n"
        "        # Validate all items before calling this method.\n"
        "        "
        if batch.all_or_nothing
        else ""
    )

    return textwrap.dedent(f"""\
        def {method_name}(
            self,
            items: list[dict[str, Any]],
            **extra_payload: Any,
        ) -> dict:
            \"\"\"
            {ep.description}

            Sends up to {batch.max_batch_size} items per request.
            \"\"\"
            {all_or_nothing_comment}payload = {{
                "{batch.payload_key}": [self._prepare_item(item) for item in items],
                **extra_payload,
            }}
            response = self._client.{ep.method.lower()}("{path_sub}", json=payload)
            response.raise_for_status()
            return response.json()

        def _prepare_item(self, item: dict[str, Any]) -> dict:
            result: dict[str, Any] = {{}}
        {field_prepare_lines}
            return result
        """)


def _render_single_method(ep: EndpointConfig, method_name: str, path: str) -> str:
    path_sub = _path_substitution(ep, path)
    return textwrap.dedent(f"""\
        def {method_name}(self, payload: dict[str, Any]) -> dict:
            \"\"\"{ep.description}\"\"\"
            response = self._client.{ep.method.lower()}("{path_sub}", json=payload)
            response.raise_for_status()
            return response.json()
        """)


def _render_field_preparation(fields: list[FieldMapping], indent: int = 8) -> str:
    pad = " " * indent
    lines: list[str] = []
    for fm in fields:
        src = fm.source_field
        dst = fm.target_field
        transforms = [t for t in fm.transformations if t != Transformation.NONE]

        if not transforms:
            if fm.required:
                lines.append(f'{pad}result["{dst}"] = item["{src}"]')
            else:
                lines.append(f'{pad}if "{src}" in item:')
                lines.append(f'{pad}    result["{dst}"] = item["{src}"]')
        else:
            getter = f'item["{src}"]' if fm.required else f'item.get("{src}")'
            chain = _transform_chain(getter, transforms)
            if fm.required:
                lines.append(f'{pad}result["{dst}"] = {chain}')
            else:
                lines.append(f'{pad}if "{src}" in item:')
                lines.append(f'{pad}    result["{dst}"] = {_transform_chain(f"item[\"{src}\"]", transforms)}')

    return "\n".join(lines)


def _transform_chain(value_expr: str, transforms: list[Transformation]) -> str:
    expr = value_expr
    for t in transforms:
        if t == Transformation.LOWERCASE:
            expr = f"str({expr}).lower()"
        elif t == Transformation.STRIP_WHITESPACE:
            expr = f"str({expr}).strip()"
        elif t == Transformation.SHA256_HASH:
            expr = f"_sha256({expr})"
        elif t == Transformation.UNIX_TIMESTAMP:
            expr = f"int({expr})"
        elif t == Transformation.PHONE_E164:
            expr = f"_normalize_phone({expr})"
    return expr


def _render_transform_helpers(spec: ConnectorSpec) -> str:
    all_transforms: set[Transformation] = set()
    for ep in spec.endpoints:
        for fm in ep.body_fields + ep.query_params:
            all_transforms.update(fm.transformations)

    helpers: list[str] = []
    if Transformation.SHA256_HASH in all_transforms:
        helpers.append(textwrap.dedent("""\
            def _sha256(value: str) -> str:
                return hashlib.sha256(value.strip().lower().encode()).hexdigest()
            """))
    if Transformation.PHONE_E164 in all_transforms:
        helpers.append(textwrap.dedent("""\
            def _normalize_phone(value: str) -> str:
                digits = "".join(c for c in value if c.isdigit())
                return f"+{digits}" if not digits.startswith("+") else digits
            """))
    return "\n\n".join(helpers)


def _path_substitution(ep: EndpointConfig, path: str) -> str:
    """Convert {pixel_id} style path templates to f-string style for the client call."""
    for param in ep.path_params:
        path = path.replace(f"{{{param}}}", f"{{self._{param}}}")
    return path


def _auth_param(spec: ConnectorSpec) -> str:
    return f"{_param_name(spec)}: str"


def _param_name(spec: ConnectorSpec) -> str:
    return _slugify(spec.auth.token_param)


def _path_params(spec: ConnectorSpec) -> list[str]:
    params: set[str] = set()
    for ep in spec.endpoints:
        params.update(ep.path_params)
    return [f"{p}: str" for p in sorted(params)]


def _auth_setup(spec: ConnectorSpec) -> str:
    from .schemas import TokenPlacement
    if spec.auth.placement == TokenPlacement.HEADER:
        header = spec.auth.header_name or "Authorization"
        return f'headers={{"{header}": f"Bearer {{self._{_param_name(spec)}}}"}},'
    return ""  # query-param auth is injected per-request in the real impl


def _class_name(api_name: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[^a-zA-Z0-9]", api_name) if w) + "Connector"


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
